### ISSUE TITLE
livox support ros2

### ISSUE THREAD

**Issue by FPSychotic** [Huguet57/LIMO-Velo#31]
Does the ros2 branch support livox?

thanks

**Comment by Huguet57** [comment]
Hey! For optimal performance in livox I would suggest using [Fast-LIO](https://github.com/hku-mars/FAST_LIO) since it's the same algorithm and theirs is already made for livox on the first place.

LIMO-Velo could be thought as an adaptation of Fast-LIO for rotational LiDARs to achieve similar high-frequency (and) real-time outputs.

**Comment by FPSychotic** [comment]
HI, I ask becaude Fast-Lio have not ros2 fork, yours have. By the way I'm using a Livox 360 degrees in a Orin NX
